### ISSUE TITLE
Control characters are not escaped when encoding strings

### ISSUE THREAD

**Issue by mtstickney** [phmarek/yason#41]
The JSON spec requires that quotation marks, reverse-solidus and the control characters U+0000 - U+001F be escaped inside strings. Yason currently outputs the control-character as-is, which can result in emitting JSON that won't be accepted by parsers.

The fix for this is straightforward, except for some questions of design: should the escapes be added to `*char-replacements*`, or should they be done in the `encode` method for strings? Unlike `\t` et al, these are easy to transform programmatically.

`*char-replacements*` isn't exported, but it feels like the sort of thing a user might want to rebind to control the optional escaping of other characters. If that were the case, the mandatory-escaping characters probably ought to be handled in the encode method, and it raises the further question of whether the replacements from `*char-replacements*` should be assumed correct, or whether they would need checking for characters that need to be escaped.

This is also somewhat related to an issue handling non-BMP unicode characters. Non-BMP characters must be encoded as an escaped UTF-16 surrogate pair; this is also a fairly easy transform, except there are so many non-BMP characters that storing them in a replacements table probably doesn't make sense.

Any thoughts, opinions, or preferences on how this gets implemented?

**Comment by hanshuebner** [comment]
I think `*char-replacements*` is the right place to make additional replacements in strings happen.  I would not bother exporting the special variable unless there is an actual request from a user and it can be demonstrated that YASON is the best place in which to make arbitrary, user-defined replacements.  My gut feeling is that if such additional mappings are required, they should be applied outside of YASON.  YASON should be concerned only with conforming to the spec.
