### ISSUE TITLE
yason:*symbol-key-encoder* not working for hash table keys

### ISSUE THREAD

**Issue by sjl** [phmarek/yason#53]
I'm trying to use the new `yason:*symbol-key-encoder*` to encode a hash table with symbols as keys, but it doesn't seem to work.

Example:

    (ql:quickload :yason)

    (defparameter *example-alist* '((:foo . 1)))
    (defparameter *example-hash-table* (make-hash-table))
    (defparameter *example-hash-table-with-string* (make-hash-table))

    (setf (gethash :foo *example-hash-table*) 1)
    (setf (gethash "foo" *example-hash-table-with-string*) 1)

Set the symbol key encoder:

    (setf yason:*symbol-key-encoder* #'yason:encode-symbol-as-lowercase)

Encoding alists with symbol keys now works as expected:

    (yason:encode-alist *example-alist*)
    ; => {"foo":1}

Hash tables with string keys work fine, as always:

    (yason:encode *example-hash-table-with-string*)
    ; => {"foo":1}

But hash tables with symbol keys still don't work:

    (yason:encode *example-hash-table*)
    ; => {
    ; => debugger invoked on a SB-PCL::NO-APPLICABLE-METHOD-ERROR in thread
    ; => #<THREAD "main thread" RUNNING {10005204C3}>:
    ; =>   There is no applicable method for the generic function
    ; =>     #<STANDARD-GENERIC-FUNCTION YASON:ENCODE (12)>
    ; =>   when called with arguments
    ; =>     (:FOO #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000006373}>).
    ; => See also:
    ; =>   The ANSI Standard, Section 7.6.6
    ; =>
    ; => restarts (invokable by number or by possibly-abbreviated name):
    ; =>   0: [RETRY] Retry calling the generic function.
    ; =>   1: [ABORT] Exit debugger, returning to top level.
    ; =>
    ; => ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION YASON:ENCODE (12)> :FOO #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDOUT* {1000006373}>) [fast-method]

**Comment by phmarek** [comment]
Thanks for the report!
