### ISSUE TITLE
skip-whitespace

### ISSUE THREAD

**Issue by don-git** [phmarek/yason#59]
The problem is that some streams are arriving in real time, and just
cause nothing is available to read now doesn't mean that the next
thing to arrive won't be whitespace.
I believe that all callers to this function continue by reading more
characters, which they expect not to be whitespace.  If so, there's
nothing lost if waiting for the next character happens here rather
than in the caller.
I see there's a newer version than mine, but it looks like the issue is still there.
In my old version my proposed fix is
defun skip-whitespace (input)
  (loop
     while (and ;; (listen input) ;; this should be removed!
                (whitespace-p (peek-char nil input)))
     do (read-char input)))

**Comment by phmarek** [comment]
I'm not sure I do understand you here.
Your issue is that the current `SKIP-WHITESPACE` function blocks when reading from a socket stream; but you would like some way to only receive full json items from the stream but not block inbetween, right?

Well, apart from completely rewriting the library into co-routines, I guess the best way forward would be to create a queue (see `LPARALLEL` or eg. `SB-CONCURRENCY:MAILBOX`), and have one thread use the normal blocking functions to read from the socket and put completed items into the queue.
Any consumer can then trivially look whether there's something to do in the queue.

**Comment by don-git** [comment]
Philipp Marek writes:
 > I'm not sure I do understand you here.

 > Your issue is that the current `SKIP-WHITESPACE` function blocks
 > when reading from a socket stream; but you would like some way to
 > only receive full json items from the stream but not block
 > inbetween, right?

No, the opposite - current code does NOT block, I think it should.
What I sent was the edited version that does block, with the
old code that causes it to not block commented out.

 > Well, apart from completely rewriting the library into co-routines,

What I propose is a one line fix (perhaps -1 line - just remove code).
Nothing complicated is required.

**Comment by phmarek** [comment]
Well, neither your "old" nor your "new" code is the code that's in the repository currently, that's what makes it harder to understand.

When I call `(YASON:PARSE stream)` with a socket-connected stream, it blocks. That's the behaviour you want, isn't it?

**Comment by don-git** [comment]
sorry, you're right - the current code
(defun skip-whitespace (input)
  (loop for c = (peek-char nil input nil nil)
     while (and c (whitespace-p c))
do (read-char input)))
appears to be equivalent to my "new" version.

**Comment by don-git** [comment]
I notice now that what is in the repository has the same version # "0.7.6"
with the sme maintainer and the same CHANGELOG as the version I have, which
includes the former code:
(defun skip-whitespace (input)
  (loop while (and (listen input)
                   (whitespace-p (peek-char nil input)))
        do (read-char input)))

Perhaps you could change these if you want people to realize that there
is some difference in the code.

**Comment by phmarek** [comment]
Thanks, yeah.

I put tags in git, but the version number in the ASDF file I didn't update.
