### ISSUE TITLE
encode-alist bug

### ISSUE THREAD

**Issue by aslakg** [phmarek/yason#64]
A json parsed to alist by yason, doesn't encode back to json, but gets an error:

Example from repl:

"{\"testdb\\/complex\":{\"nested\":{\"#\":\"testdb\\/complex\\/nested\"},\"_\":{\">\":{\"nested\":1624963327298},\"#\":\"testdb\\/complex\"}}}"

> (yason:parse *)
(("testdb/complex"
  ("_" ("#" . "testdb/complex") (">" ("nested" . 1624963327298)))
  ("nested" ("#" . "testdb/complex/nested"))))

> (yason:encode-alist *)
{"testdb/complex":[["_",["#"
; Debugger entered on #<TYPE-ERROR expected-type: LIST datum: "testdb/complex">

I would instead expect to get back a string with the equivalent json of what was parsed.

**Comment by phmarek** [comment]
The default is to parse into `hash-table`s, which can be reversed:

```lisp
(yason:parse
   "{\"testdb\/complex\":{\"nested\":{\"#\":\"testdb\/complex\/nested\"},\"_\":{\">\":{\"nested\":1624963327298},\"#\":\"testdb\/complex\"}}}")
;; #<HASH-TABLE :TEST EQUAL :COUNT 1 {100AFC3C13}>
(yason:with-output-to-string* () (yason:encode *))
;; "{\"testdb/complex\":{\"nested\":{\"#\":\"testdb/complex/nested\"},\"_\":{\">\":{\"nested\":1624963327298},\"#\":\"testdb/complex\"}}}"
```

When you use `(let ((yason:*parse-object-as* :alist)) (yason:parse ...))`, the transformation isn't reversible without some effort; but it might be easier to use, that's why this special variable exists.

(Why did you have the forward slashes `/` escaped?)

**Comment by aslakg** [comment]
Sorry, forgot to mention that (setf yason:*parse-object-as* :alist)
what issued beforehand. 
It's precisely that the transformation isn't reversible that is the problem. My processing code needs to work with alists.
Currently I'm forced to use yason to parse, and cl-json to convert back to json string .
Neither yason by itself nor cl-json is able to do a reversible transformation (cl-json because it turns strings into symbols, and changes case on any character following a number) by itself.
It seems reasonable to me that parsing and reencoding should work...

**Comment by phmarek** [comment]
> It seems reasonable to me that parsing and reencoding should work...

Yes, of course.
But lists could be used for objects or arrays, so it's not well-defined what to do with such an input...

Can you use hash-tables and the access library (https://quickref.common-lisp.net/access.html#Introduction)?

**Comment by aslakg** [comment]
Ah, I get what you're saying. I think CL-JSON explicitly does not support lists in the json, that's why it works there.
Sure, I could probably go that hash-table route, since I'm already using access. Thanks.
One alternative would be to have a settings variable / configuration to choose the behaviour for alists to default to objects only, another is to mandate that json arrays in alists must be arrays or vectors. But there could be consequences for existing code of course.
