### ISSUE TITLE
Quicklisp out of sync with this version of Yason?

### ISSUE THREAD

**Issue by sabracrolleton** [phmarek/yason#65]
I am not seeing *symbol-encoder* in the version distributed by quicklisp. Did something get out of sync moving from hans github to here?

**Comment by phmarek** [comment]
Well, the HTTP accesses get redirected; but perhaps the QL pulling script isn't?

I asked on https://github.com/quicklisp/quicklisp-projects/issues/401.

**Comment by Symbolics** [comment]
It looks like this was closed in the quicklisp repo. Should this issue be closed here?

**Comment by phmarek** [comment]
Yeah, thanks!
