### ISSUE TITLE
YASON:ENCODE requires a stream to output

### ISSUE THREAD

**Issue by fukamachi** [phmarek/yason#69]
After 7daea00, `yason:encode` always requires a stream for the second argument. Did the API change accidentally, or intended?

```
(yason:encode (make-hash-table))

Unhandled UNBOUND-VARIABLE in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                        ***10014EC073***>:
  The variable YASON::*JSON-OUTPUT* is unbound.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING ***10014EC073***>
0: ((:METHOD YASON:ENCODE (HASH-TABLE)) #<HASH-TABLE :TEST EQL :COUNT 0 ***100447DB63***>) [fast-method,optional]
```

In [the documentation](http://phmarek.github.io/yason/), it says `Stream defaults to *STANDARD-OUTPUT*.`.

```
[Generic function]
encode object &optional stream => object

    Encode object in JSON format and write to stream. May be specialized by applications to perform specific rendering. Stream defaults to *STANDARD-OUTPUT*. 
```

**Comment by phmarek** [comment]
Hmmm, yeah, right, the docstring is wrong since quite some time.
Defaulting to `*STANDARD-OUTPUT*` was already broken for aggregates (arrays, dicts) -- now it's only more explicit.

Thanks, I changed the docstring and added a few tests in 344572beb2c831bc72432a9328812596a83174f0.
