### ISSUE TITLE
Custom encoding for a specific key in an a/p list?

### ISSUE THREAD

**Issue by Symbolics** [phmarek/yason#70]
I am using yason to encode alists for specifying [Vega-Lite](https://vega.github.io/vega-lite/) plots. This works, but is verbose, so I'm switching over to plists. This works well, with the exception I'm asking about here. For example:

```lisp
  (yason:with-output (*standard-output* :indent t)
    (yason:encode `("$schema" "https://vega.github.io/schema/vega-lite/v5.json"
			     :description "A simple bar chart with embedded data."
			      :mark bar
			      :data (:values #((:x ,mtcars:mpg
						:y ,mtcars:hp)))
			      :encoding (:x (:field a :type nominal :axis ("labelAngle" 0))
					 :y (:field b :type quantitative)))))
```
The problem is in the `:data` encoding. Vega-Lite is a bit clumsy with data specifications, having several variations; making the user construct a plist for the data is unnecessarily cumbersome and I want to simplify it.

My first thought was to create a method for `encode` specialising on the `:data` object:

```
(defmethod yason:encode ((object (eql :data)) &optional (stream yason::*json-output*))
  (write-string "found :data" stream)
  object)
```
But that doesn't work because [encode-plist](https://github.com/phmarek/yason/blob/344572beb2c831bc72432a9328812596a83174f0/encode.lisp#L216)'s object is key/value pairs, and everything up that call chain is a function, e.g. `encode-key/value`, etc.

I'm currently thinking of creating a `data` function that will return a properly constructed alist and pass it via backquote/comma (like the two vectors are in the first example: ,mtcars:mpg, which are symbol macros), `:data ,(data mtcars:mpg ...`. However turning the data into an alist isn't quite as straightforward as it appears because, depending on the data types and format, I need to write _another_ key/value pair to the JSON specification to transform the data. This makes me think I'll need to write to the output stream to handle this properly.

Does anyone here have any ideas on how to handle this use case? At worst I can create a version of `encode-plist` and look for `:data` in the loop, but this seems like a blunt instrument, and being able to override processing of a single key in the key/value pair a more generally useful thing to be able to do.

**Comment by phmarek** [comment]
Well, your idea with some helper function sounds good:

```lisp
(let ((yason:*symbol-encoder* #'yason:encode-symbol-as-lowercase))
  (yason:with-output (*standard-output* :indent t)
    (yason:encode `("$schema" "https://vega.github.io/schema/vega-lite/v5.json"
                    :description "A simple bar chart with embedded data."
                    :mark bar
                    :data ,(my-data-function ...)
                    :encoding (:x (:field a :type nominal :axis ("labelAngle" 0))
                               :y (:field b :type quantitative))))))
```

Another idea would be to replace the whole `(yason:with-output ...)` block with your own function, with an arglist like `(&key description mark data encoding)` - that can do anything you like with the `:data` argument, of course.

Or, brainstorming here... how about something like `ggplot` does, incrementally contructing an object from multiple parts?


BTW: A method on `:data` might conflict with any other JSON data on your machine... the method would need to check a special variable that you bind locally.

**Comment by Symbolics** [comment]
Thanks. I'll close this now. I already use something like ggplot with the alist version. I'll put something together with plists that is both additive and uses helpers.
