### ISSUE TITLE
Problem installing YASON

### ISSUE THREAD

**Issue by LyleJG** [phmarek/yason#74]
Hello,

Thank you very much for maintaining YASON. I am installing it today (0.8.3), but there seems to be some problems with the tests (see below).

I would be grateful if you could help out with this issue.

Best regards,
Lyle
........................
Lyle J. Graham
Neurophysiology of Visual Computation
Centre Giovanni Borelli - CNRS UMR 9010
Université Paris Cité
45 rue des Saint-Pères, 75006 Paris, FRANCE
Tel: [33]6.01.36.66.74
http://lyle.neurophysics.eu/
..................................

SH> (unit-test::run-all-tests :unit :yason)
Running "parser.basic" ...
=> 2 passed.
Running "parser.basic-with-whitespace" ...
=> 2 passed.
Running "dom-encoder.basic" ...
=> 2 passed.
Running "dom-encoder.w-o-t-s*" ...
Test "dom-encoder.w-o-t-s*" issued error No matching method for the generic
                                         function
                                         #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
                                           {28F06519}>,
                                         when called with arguments
                                         (#<YASON::JSON-OUTPUT-STREAM
                                            {60F8DAF5}>).
error: (Test "dom-encoder.w-o-t-s*")                                            CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {60F8DAF5}>).
=> 1 crashed.
Running "dom-encoder.w-o" ...
Test "dom-encoder.w-o" issued error No matching method for the generic function
                                    #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
                                      {28F06519}>,
                                    when called with arguments
                                    (#<YASON::JSON-OUTPUT-STREAM {6115294D}>).
error: (Test "dom-encoder.w-o")                                                 CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {6115294D}>).
=> 1 crashed.
Running "dom-encoder.indentation" ...
error: (WITH-OUTPUT-TO-STRING (S) ..)                                           CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {611B0745}>).
error: (REMOVE-IF #'WHITESPACE-CHAR-P ..)                                       CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {61257D7D}>).
error: (REMOVE-IF #'WHITESPACE-CHAR-P ..)                                       CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {612A8ABD}>).
error: (REMOVE-IF #'WHITESPACE-CHAR-P ..)                                       CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {612A92B5}>).
=> 1 passed. 4 crashed.
Running "dom-encoder.object-indentation" ...
error: (WITH-OUTPUT-TO-STRING (S) ..)                                           CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {612B25E5}>).
=> 1 crashed.
Running "dom-encoder.empty-array-and-object-indentation" ...
=> 1 passed.
Running "stream-encoder.basic-array" ...
=> 1 passed.
Running "stream-encoder.basic-object" ...
=> 1 passed.
Running "stream-encode.unicode-string" ...
error: (WITH-OUTPUT-TO-STRING (S) ..)                                           CRASHES.
Error was: Type-error in KERNEL::OBJECT-NOT-TYPE-ERROR-HANDLER:
              119070 is not of type (UNSIGNED-BYTE 16)
=> 1 crashed.
Running "stream-encoder.application-struct" ...
=> 1 passed.
Running "recursive-alist-encode" ...
=> 1 passed.
Running "symbols-as-keys" ...
=> 2 passed.
Running "symbols-as-ht-keys" ...
error: (LET* ((*SYMBOL-KEY-ENCODER* #'ENCODE-SYMBOL-AS-LOWERCASE)) ..)          CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {6033DD2D}>).
=> 1 crashed.
Running "ENCODE-as-obj-value" ...
error: (WITH-OUTPUT-TO-STRING (*STANDARD-OUTPUT*) ..)                           CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {603A70BD}>).
=> 1 crashed.
Running "ENCODE-as-obj-value-2" ...
error: (WITH-OUTPUT-TO-STRING (*STANDARD-OUTPUT*) ..)                           CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {603F6CFD}>).
=> 1 crashed.
Running "object-in-array" ...
error: (WITH-OUTPUT-TO-STRING (*STANDARD-OUTPUT*) ..)                           CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {6049DE25}>).
=> 1 crashed.
Running "output-to-string-with-indentation" ...
error: (WITH-OUTPUT-TO-STRING* (INDENT 2 STREAM-SYMBOL S) (ENCODE #(1 2 3)))    CRASHES.
Error was: No matching method for the generic function
           #<STANDARD-GENERIC-FUNCTION EXTENSIONS:STREAM-LINE-COLUMN (3)
             {28F06519}>,
           when called with arguments (#<YASON::JSON-OUTPUT-STREAM {604F640D}>).
=> 1 crashed.
Running "parse-double-float" ...
=> 1 passed.
Running "parse-ordering-hash" ...
=> 3 passed.
Running "parse-ordering-alist" ...
=> 1 passed.
Running "parse-ordering-plist" ...
=> 1 passed.
Running "duplicate-key" ...
=> 2 passed.

====================================
35 tests total.
   22 passed.
   13 crashed.
NIL
SH>

**Comment by LyleJG** [comment]
Hi Philipp,
Thanks for your reply. Here is the info:

CMU Common Lisp 21d (21D Unicode)
Loaded subsystems:
    Unicode 1.29 with Unicode version 6.2.0
    Python 1.1, target Intel x86/sse2
    CLOS based on Gerd's PCL 2010/03/19 15:19:03
    Gray Streams Protocol Support
    CLX X Library MIT R5.02


Best,
Lyle
--------------------------------------------------------------
Lyle J. Graham
Neurophysiology of Visual Computation
Centre Giovanni Borelli - CNRS UMR 9010
Université Paris Cité
45 rue des Saint-Pères, 75006 Paris, FRANCE
Tel: [33]6.01.36.66.74
http://lyle.neurophysics.eu/
--------------------------------------------------------------

**Comment by rtoy** [comment]
I'll take a look at this, although I've never used simple-streams for anything.  Do I need to download and build yason to reproduce this?

**Comment by LyleJG** [comment]
Great to see a long time CMUCL guru weighing in!

I don't know if this question is posed to me, but in any event, I am starting from a fresh Lisp (under Sime, with quicklisp installed):

(ql:quickload "alexandria")
(ql:quickload "TRIVIAL-GRAY-STREAMS")
(ql:quickload "UNIT-TEST")
(asdf::load-asd "/home/lyle/Downloads/yason-0.8.3/yason.asd")
(asdf::load-system :yason)
(compile-file "/home/lyle/Downloads/yason-0.8.3/test.lisp" :load t)
(unit-test::run-all-tests :unit :yason)

Thanks,
Lyle

**Comment by rtoy** [comment]
Hey Lyle! Long time!

I followed your steps and can reproduce the issue.  From the first failed test, I've simplified it a little to:
```
(let ((s (make-string-output-stream)))
  (unwind-protect
      (progn
	(let ((yason::*json-output*
	       (make-instance 'yason::json-output-stream
			      :output-stream s
			      :indent 2)))
	  (stream-line-column yason::*json-output*)))))

No matching method for the generic function
#<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN (3) {63F27829}>, when called
with arguments (#<YASON::JSON-OUTPUT-STREAM {6218CDC5}>).
   [Condition of type PCL::NO-APPLICABLE-METHOD-ERROR]
```

I've never really worked with gray-streams, and it's been a long time
since I worked with classes, but
```
* (subtypep 'yason::json-output-stream 'fundamental-character-output-stream)

T
T
```

But
```
* (describe 'stream-line-column)
STREAM-LINE-COLUMN is an external symbol in the EXTENSIONS package.
Function: #<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN (1) {63AD0D41}>
#<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN (1) {63AD0D41}> is a generic function.
Its lambda-list is:
  (STREAM)
Generic function documentation:
  "This function returns the column number where the next character
  will be written, or NIL if that is not meaningful for this stream.
  The first column on a line is numbered 0.  This function is used in
  the implementation of PPRINT and the FORMAT ~T directive.  For every
  character output stream class that is defined, a method must be
  defined for this function, although it is permissible for it to
  always return NIL."
Its methods are:
  1: STREAM-LINE-COLUMN ((STREAM LISP::CHARACTER-OUTPUT-STREAM))
```
and
```
* (subtypep 'yason::json-output-stream 'lisp::character-output-stream)
NIL
T
```
so the error kind of makes sense.

Does this mean we need to define a `stream-line-column` method for `yason::json-ouptut-stream`?  The [comment in gray-streams.lisp](https://gitlab.common-lisp.net/cmucl/cmucl/-/blob/master/src/pcl/gray-streams.lisp#L216) seems to say so.

I haven't used gray streams, so I'm learning this is as I go.  (But I see that slime/swank defines a method for `slime-output-stream` which is a subclass of `fundamental-character-output-stream`.)

**Comment by rtoy** [comment]
Hey Lyle! Long time!

I followed your steps and can reproduce the issue.  From the first failed test, I've simplified it a little to:
```
(let* ((stg (yason:with-output-to-string* (:indent 2)
	      (yason:encode yason-test::*basic-test-json-dom*)))
       (result (yason:parse stg)))
  result)

No matching method for the generic function
#<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN (3) {63F27829}>, when called
with arguments (#<YASON::JSON-OUTPUT-STREAM {6218CDC5}>).
   [Condition of type PCL::NO-APPLICABLE-METHOD-ERROR]
```

I've never really worked with gray-streams, so I'm learning as a I go.  The backtrace is informative:

```
0: ("DEFMETHOD NO-APPLICABLE-METHOD (T)" #<unused-arg> #<unused-arg>
    #<STANDARD-GENERIC-FUNCTION STREAM-LINE-COLUMN (3) {63F27829}>
    (#<YASON::JSON-OUTPUT-STREAM {63425285}>))
1: (PRETTY-PRINT::MAKE-PRETTY-STREAM #<YASON::JSON-OUTPUT-STREAM {63425285}>)
2: (PRETTY-PRINT::OUTPUT-PRETTY-OBJECT 1
                                       #<YASON::JSON-OUTPUT-STREAM {63425285}>)
3: (PRINC 1 #<YASON::JSON-OUTPUT-STREAM {63425285}>)
0] fr 1
(PRETTY-PRINT::MAKE-PRETTY-STREAM #<YASON::JSON-OUTPUT-STREAM {63425285}>)
1] sou 2
(BUFFER-START-COLUMN (OR (#:***HERE*** (LISP::CHARPOS TARGET)) 0) :TYPE COLUMN)
```
So it looks like we need to set the `buffer-start-column` by figuring out the `charpos` of the stream, and `charpos` calls `stream-line-column` for a `fundamental-stream`.

I haven't figure out why `stream-line-column` isn't defined for this, but it does seem like `fundamental-output-stream` doesn't any kind of column slot where `stream-line-column` could get the column.

**Comment by LyleJG** [comment]
Hi,
This stuff is beyond my compentence, so forgive me if the following is obvious:

After evaluating the following to define a default:

(cl:in-package :cl-user)
(defmethod stream-line-column (stream) nil)


RUN-ALL-TESTS gives:

(unit-test::run-all-tests :unit :yason)
...
Running "stream-encode.unicode-string" ...
error: (WITH-OUTPUT-TO-STRING (S) ..)                                           CRASHES.
Error was: Type-error in KERNEL::OBJECT-NOT-TYPE-ERROR-HANDLER:
              119070 is not of type (UNSIGNED-BYTE 16)
=> 1 crashed.
...
====================================
39 tests total.
   38 passed.
   1 crashed.
NIL
CL-USER> 

I'm not sure why there are 39 tests now, instead of 35 as before.
Lyle

**Comment by rtoy** [comment]
Haven't looked at that particular issue yet, but according to the [gray-stream-proposal](http://www.nhplace.com/kent/CL/Issues/stream-definition-by-user.html), `stream-line-column` : 

> This function returns the column number where the next character
> will be written, or NIL if that is not meaningful for this
> stream. The first column on a line is numbered 0.  This function is
> used in the implementation of PPRINT and the FORMAT ~T directive.
> For every character output stream class that is defined, a method
> must be defined for this function, although it is permissible for it
> to always return NIL.

So, yason must define a method for this.  I'll take a look a bit later to see why the test is failing, but it seems something is expecting a 16-bit unsigned int, and was getting something bigger than that.

**Comment by LyleJG** [comment]
I wonder what is "missing" from CMUCL (or from the :gray-streams module?), since I imagine yason works with other implementations...
L

**Comment by rtoy** [comment]
Ah, here is the offending part of the test:
```
(deftest :yason "stream-encode.unicode-string"
  (test-equal "\"ab\\u0002 cde \\uD834\\uDD1E\""
              (with-output-to-string (s)
                (yason:encode (format nil "ab~C cde ~C" (code-char #x02) (code-char #x1d11e)) s))))
```

In cmucl, `char-code-limit` is 65536, so `#x1d11e` won't fit. However, in cmucl, all strings use UTF-16 encoding, so you'll need to replace the character with the corresponding surrogate pair.  If it's necessary to test these, then use `lisp:surrogates` to find the surrogate pairs.

I didn't check, but I assume `yason:encode` will need to know that the string is utf-16 encoded instead of utf-32.

**Comment by LyleJG** [comment]
Wow. That's pretty down there at the bit-banging level.

**Comment by rtoy** [comment]
Took a quick peek at `yason:encode`.  I think `escape-string-to-stream` needs to be modified to support cmucl's utf-16 strings.  Not sure about the iteration across the string, but there's a case where non-BMP characters need to be converted to a surrogate pair.  In cmucl, this is already a surrogate pair.  Or maybe use `lisp:with-string-codepoint-iterator` to iterate over the string returning codepoints.  Or, being wasteful, but easy, use `lisp::string-codepoints` to convert the string into a list of codepoints.

I can help with this.  Once it's decided how the offending test is to be modified to handle lisps where `char-code-limit` is too small to hold a full unicode codepoint.

**Comment by rtoy** [comment]
> 



> wonder what is "missing" from CMUCL (or from the :gray-streams module?), since I imagine yason works with other implementations...

Yeah, I was  wondering the same thing.  But the docs from the gray-stream proposal make it pretty clear you have to define your own `strream-line-column` method.  So I don't know how other lisps handle this.  Maybe their pretty-printer doesn't need to use `stream-line-column`?

**Comment by rtoy** [comment]
Ok, here is a potential fix.

For `encode.lisp` add:
```
;; Cmucl needs STREAM-LINE-COLUMN defined to work.  Always Returning
;; NIL is ok, and allowed by the gray-streams proposal.
#+cmucl
(defmethod ext:stream-line-column ((stream json-output-stream))
  nil)
```
and use this version of `encode`:
```
;; Cmucl strings are utf-16 encoded, so a different implementation is needed.
#+cmucl
(defun escape-string-to-stream (string stream)
  (lisp:with-string-codepoint-iterator (next-codepoint string)
    (loop
      (multiple-value-bind (morep codepoint)
	  (next-codepoint)
	(unless morep
	  (return))
	(cond
	  ((<= #x0000 codepoint #x001F)
	   ;; Control characters (U+0000 - U+001F) must be escaped.
	   (format stream "\\u~4,'0X" codepoint))
          ((<= #x010000 codepoint #x10FFFF)
	   ;; Non-BMP characters must be escaped as a UTF-16 surrogate pair.
	   (write-surrogate-pair-escape codepoint stream))
	  (t
	   ;; Codepoint is in the BMP.  Use the replacement if
	   ;; available or just output the character.
	   (let ((replacement (gethash (code-char codepoint) *char-replacements*)))
	     (if replacement
		 (write-string replacement stream)
		 (write-char (code-char codepoint) stream)))))))))
```

Finally, update "test.lisp":
```
#+cmucl
(deftest :yason "stream-encode.unicode-string"
  (test-equal "\"ab\\u0002 cde \\uD834\\uDD1E\""
              (with-output-to-string (s)
                (yason:encode (format nil "ab~C cde ~{~C~}"
				      (code-char #x02)
				      (multiple-value-list (lisp:surrogates #x1d11e)))
			      s))))
```

Making these changes allows the unit tests to run to completion without errors.

**Comment by rtoy** [comment]
Not sure about the `stream-line-column` method.  This is correct, but maybe trivial-gray-streams should be the one to handle this.

**Comment by phmarek** [comment]
Raymond, thanks a lot for the quick and extensive help!!
I'll take these changes into `YASON`.

> Not sure about the `stream-line-column` method. This is correct, but maybe `trivial-gray-streams` should be the one to handle this.

Yeah, I think so too that this would be the right place.
Should I (temporarily) take that in as well?

**Comment by rtoy** [comment]
I filed https://github.com/trivial-gray-streams/trivial-gray-streams/issues/12; let's see what happens.  In the meantime, I'd add the stream-line-column method for cmucl so that YASON works with cmucl for now.  If other lisps have this problem, we know what to do.

**Comment by rtoy** [comment]
I think the following is easier to read; I forgot that cmucl has extended the extended loop to allowing getting codepoints from a string:
```
(defun escape-string-to-stream (string stream)
  (loop for codepoint being the codepoint of string
	do
	   (cond
	     ((<= #x0000 codepoint #x001F)
	      ;; Control characters (U+0000 - U+001F) must be escaped.
	      (format stream "\\u~4,'0X" codepoint))
             ((<= #x010000 codepoint #x10FFFF)
	      ;; Non-BMP characters must be escaped as a UTF-16
	      ;; surrogate pair.  Cmucl strings already use surrogate
	      ;; pairs, but do it this way to get the pairs in the
	      ;; desired order.
	      (write-surrogate-pair-escape codepoint stream))
	     (t
	      ;; Codepoint is in the BMP.  Use the replacement if
	      ;; available or just output the character.
	      (let ((replacement (gethash (code-char codepoint) *char-replacements*)))
		(if replacement
		    (write-string replacement stream)
		    (write-char (code-char codepoint) stream)))))))
```

**Comment by rtoy** [comment]
I think there's another problem with yason:  `parse-unicode-escape` seems to assume that the surrogate pair can be converted to a character.  Of course that's not possible with cmucl's utf-16 strings.  The surrogate pair should be left alone and inserted into the string directly.

It would be helpful if there were tests for parsing surrogates.  I guess `parse-unicode-escape` and `parse-string` would need to be changed to support cmucl.

**Comment by rtoy** [comment]
Oh, https://github.com/trivial-gray-streams/trivial-gray-streams/issues/12, it's clear that trivial-gray-streams exports `stream-line-column` so this the following is fine and could be used for all lisps, not just cmucl:
```
(defmethod trivial-gray-streams:stream-line-column ((stream json-output-stream))
  nil)
```

I'll leave it to you to decide if you want to do this for all lisps or just cmucl.

**Comment by rtoy** [comment]
Here is my guess on how to do parsing for cmucl:
```
diff --git a/parse.lisp b/parse.lisp
index 7c957a6..e2d5545 100644
--- a/parse.lisp
+++ b/parse.lisp
@@ -61,9 +61,14 @@
             (when (not (and (>= tail-code #xdc00)
                             (<= tail-code #xdfff)))
               (error "Lead Surrogate without Tail Surrogate"))
+	    #-cmucl
             (code-char (+ #x010000
                           (ash (- char-code #xd800) 10)
-                          (- tail-code #xdc00)))))
+                          (- tail-code #xdc00)))
+	    ;; Cmucl strings use utf-16 encoding.  Just return the two
+	    ;; surrogate chars as is.
+	    #+cmucl
+	    (values (code-char char-code) (code-char tail-code))))
         (code-char char-code))))
 
 (defun parse-string (input)
@@ -94,7 +99,16 @@
                (#\n (outc #\Newline))
                (#\r (outc #\Return))
                (#\t (outc #\Tab))
-               (#\u (outc (parse-unicode-escape input)))))
+               (#\u
+		#-cmucl
+		(outc (parse-unicode-escape input))
+		#+cmucl
+		(multiple-value-bind (char tail)
+		    (parse-unicode-escape input)
+		  (outc char)
+		  ;; Output the surrogate as is for cmucl.
+		  (when tail
+		    (outc tail))))))
             ((and (or (whitespace-p (peek))
                       (eql (peek) #\:))
                   (not string-quoted))
```

Here is a simple test for this, but I didn't test the non-cmucl version, though:
```
#-cmucl
(deftest :yason "surrogate"
  (test-equal (string (code-char #x1d11e))
	      (yason:parse "\"\\ud834\\udd1e\"")))

#+cmucl
(deftest :yason "surrogate"
  (test-equal '(#xd834 #xdd1e)
	      (map 'list #'char-code (yason:parse "\"\\ud834\\udd1e\""))))
```

**Comment by rtoy** [comment]
Perhaps this is a slightly better test:
```
(deftest :yason "surrogate"
  ;; Cmucl uses utf-16 strings, so the result has the surrogate pair
  ;; in the parsed string.
  (test-equal #-cmucl
	      (list (char-code #\a) #x1d11e)
	      #+cmucl
	      (list (char-code #\a) #xd834 #xdd1e)
	      (map 'list #'char-code (yason:parse "\"a\\ud834\\udd1e\""))))
```

**Comment by phmarek** [comment]
> Oh, in [trivial-gray-streams/trivial-gray-streams#12](https://github.com/trivial-gray-streams/trivial-gray-streams/issues/12), it's clear that trivial-gray-streams exports `stream-line-column` so the following is fine and could be used for all lisps, not just cmucl:
> 
> ```
> (defmethod trivial-gray-streams:stream-line-column ((stream json-output-stream))
>   nil)
> ```
> 
> I'll leave it to you to decide if you want to do this for all lisps or just cmucl.

On SBCL I see that `trivial-gray-streams:fundamental-character-output-stream` (which is the superclass of `json-output-stream`) already has a method, from `SB-GRAY:FUNDAMENTAL-CHARACTER-OUTPUT-STREAM`.

So I'll only add that method for cmucl.

Thanks for the parsing-patch and the test; I'll take a look at that and get back to you.


Thanks a lot!

**Comment by rtoy** [comment]
I filed https://gitlab.common-lisp.net/cmucl/cmucl/-/issues/147 for this.

**Comment by LyleJG** [comment]
Hi Raymond.
Until there is a CMUCL release that handles this issue, can you define the necessary patch that can be loaded into 21d so that we can use Yason?
Thanks!
Lyle

**Comment by phmarek** [comment]
9c022bdc4baf8c03d724c551fd991ab7da39e8b4

Thanks, Lyle, for the report, and Raymond for all the help!

**Comment by rtoy** [comment]
> Hi Raymond. Until there is a CMUCL release that handles this issue, can you define the necessary patch that can be loaded into 21d so that we can use Yason? Thanks! Lyle

The latest commit should have everything you need to run YASON.  If it still fails, please let us know.

**Comment by rtoy** [comment]
I downloaded the most recent version.  One test fails because it didn't get an updated version for cmucl.  See the proposed solution for cmucl in https://github.com/phmarek/yason/issues/74#issuecomment-1278300854

**Comment by rtoy** [comment]
To be clear, you need the updated test and the new `escape-string-to-stream`.  The version in https://github.com/phmarek/yason/issues/74#issuecomment-1279590827 is easier to read, I think.

**Comment by phmarek** [comment]
> I downloaded the most recent version. One test fails because it didn't get an updated version for cmucl. See the proposed solution for cmucl in [#74 (comment)](https://github.com/phmarek/yason/issues/74#issuecomment-1278300854)

Well, I've got the method (conditionally for CMUCL) in `YASON` now too... so what does still fail?
On SBCL all tests run successfully.

**Comment by rtoy** [comment]
The remaining issue is that yason assumes strings can hold the full unicode codepoint.  That's not possible with cmucl which has a char-code-limit of 65536.  Thus, strings in cmucl use utf-16.  The test `stream-encode.unicode-string` fails because of that.  It needs to be updated as mentioned in https://github.com/phmarek/yason/issues/74#issuecomment-1278300854.  But if you update the test, cmucl can't encode the string.  You also need to change `escape-string-to-stream` to handle cmucl's utf-16 strings.  You can use the version in https://github.com/phmarek/yason/issues/74#issuecomment-1278300854 or the version in https://github.com/phmarek/yason/issues/74#issuecomment-1279590827 which I find easier to read.

**Comment by phmarek** [comment]
Ah yeah, you're right.

Like 34c32efadad4b8f2285f81fba3970f5672cfa4bb?

**Comment by rtoy** [comment]
That  doesn't work because `(code-char #x1d11e)` doesn't work in cmucl; it signals an error.  To keep the test for cmucl, you need to do something like:
```
(deftest :yason "stream-encode.unicode-string"
  (test-equal "\"ab\\u0002 cde \\uD834\\uDD1E\""
              (with-output-to-string (s)
                (yason:encode (format nil "ab~C cde ~{~C~}"
				      (code-char #x02)
				      (multiple-value-list (lisp:surrogates #x1d11e)))
			      s))))
```

If you do this, then `escape-string-to-stream` needs to be updated because it assumes strings can hold things outside the BMP.  Strings in cmucl can't and uses surrogate pairs.  So that function needs to changed for cmucl as shown in https://github.com/phmarek/yason/issues/74#issuecomment-1279590827.

If you like, I can provide a pull request for you to look at.

**Comment by rtoy** [comment]
See #75 for a fix.

**Comment by rtoy** [comment]
Thanks for landing #75.

@LyleJG, I think yason should work fine with cmucl now.  Give it a try with the latest git HEAD.  I ran all 48 tests successfully.

If you run into any isues, file a new issue and mention me so I get a notification.

Good luck!

**Comment by LyleJG** [comment]
Dear all,
Sorry for the late reply - but thanks very much for these updates! The
tests all run ok now.
Best,
Lyle

--------------------------------------------------------------
Lyle J. Graham
Neurophysiology of Visual Computation
Centre Giovanni Borelli - CNRS UMR 9010
Université Paris Cité
45 rue des Saint-Pères, 75006 Paris, FRANCE
Tel: [33]6.01.36.66.74
http://lyle.neurophysics.eu/
--------------------------------------------------------------

**Comment by rtoy** [comment]
Fantastic! Thanks for testing.

**Comment by LyleJG** [comment]
yes, and I even get a nice list of hash tables from reading a json file of
interest. Perfect!
