### ISSUE TITLE
encoding JSON array delegating encoding to other function

### ISSUE THREAD

**Issue by cage2** [phmarek/yason#79]
Hi!

Likely I am not able to understand how to encode object to JSON using this library.

I have a function like this: 

``` lisp
(defgeneric  encode-to-json (object stream))

(defmethod encode-to-json ((object CLASS-NAME) stream)
 ; encode an instance of CLASS-NAME to stream
)
```

now let's say i would want to encode a list of the aforementioned instances in a JSON array, so i wrote:

``` lisp
(defmethod encode-to-json ((object list) stream)
   (yason:with-output (stream)
    (yason:with-array ()
      (loop for item in object do
        ;; **problem here**
          (encode-to-json item stream)))))
```

I tryed to use `(yason:encode-array-element (encode-to-json item stream))`  but the fact is that is responsibility of the `encode-json-function` to encode, what i need is something like that:

``` lisp
(defmethod encode-to-json ((object list) stream)
   (yason:with-output (stream)
    (yason:with-array ()
      (loop for item in object do
        (yason:with-array-element   ; this macro does not exists yet
          (encode-to-json item stream))))) => "[encoded-object-1, encoded-object-2..., encoded-object-n]"
```
This seems to me similar to what `yason:with-object` does.

I have checked the code and seems `encode-array-element` could be used to get `yason:with-array-element`, i could even try to send a patch if this is a good idea.

Otherwise i am just doing it wrong, in this case an hit to solve this issue would be very appreciated. :))

Thanks in advance and happy new year!
C.

**Comment by phmarek** [comment]
Basic types like lists are handled internally in `YASON`.

```lisp
(let ((data (list 1 2 3 4)))
  (yason:with-output (*standard-output*)
    (yason:encode data)))
```
gives you `[1,2,3,4]`; you can ask for indentation in the `WITH-OUTPUT` arguments, or use `WITH-OUTPUT-TO-STRING*` if that matches your usecase better.

**Comment by cage2** [comment]
Hi @phmarek !

Your message helped me to realize my mistake, I have specialized `encode' on my class and serialization of lists works now, thanks a lot!!

Bye!
C.
